name: Test local app in a docker container (Playwright)
on:
  push:
    branches: [main, master]
  workflow_dispatch:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]
permissions:
  contents: write
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      # checkout application code
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Checkout project
      # install the dependencies
        run: npm install --legacy-peer-deps
      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            /usr/local/bin/docker
          key: ${{ runner.os }}-npm-${{ hashFiles('**/*.lock') }}
      # run Docker build and run image
      - name: Run tests in a container
        run: |
          npx playwright install chrome
          sh ./scripts/docker_build_and_run.sh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: report/allure-report
          retention-days: 30
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report/allure-report
